version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: BDS_project
      POSTGRES_PASSWORD: bds_postgres
      POSTGRES_DB: car_service
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

